// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Cafe Value",
  domain: "www.cafevaluecannabisdispensary.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "654 Spadina Ave, Toronto, ON M5S 2H7",
  streetAddress: "654 Spadina Ave",
  postalCode: "M5S 2H7",
  phone: "(437) 577-2589",
  phoneIntl: "+14375772589",
  neighborhood: "The Annex / Spadina",
  nearbyAreas: ["Spadina Ave", "The Annex", "Bloor St W", "Harbord Village", "University of Toronto", "Spadina Station", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6631",
  longitude: "-79.4010",
  hours: ["Open 24 Hours"],
  seoTitle: "Cafe Value | Weed Dispensary in Toronto",
  metaDescription: "Cafe Value is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Spadina Ave", "The Annex", "Bloor St W"],
  introVariant: "Welcome to Cafe Value, a weed dispensary at 654 Spadina Ave in Toronto. Adults 19+ can browse cannabis flower, pre-rolls, edibles, THC vapes, concentrates, CBD products, and accessories. If you are looking for a cannabis store near The Annex or a weed shop near Spadina, visit the store page and menu categories for details.",
  neighborhoodDescription: "Located in the vibrant The Annex / Spadina district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Metered street parking is available along Spadina Avenue",
  transitNote: "Steps from Spadina subway station and easily accessible via TTC streetcar and subway routes.",
  sectionTitle: "Serving Customers Near The Annex in Toronto"
};
