// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Cafe Value",
  domain: "cafevaluecannabisdispensary.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "654 Spadina Ave, Toronto, ON M5S 2H7",
  streetAddress: "654 Spadina Ave",
  postalCode: "M5S 2H7",
  phone: "(437) 577-2589",
  phoneIntl: "+14375772589",
  neighborhood: "The Annex / Spadina",
  nearbyAreas: ["Spadina Ave", "The Annex", "Bloor St W", "Harbord Village", "University of Toronto", "Spadina Station", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.app.goo.gl/uX3f5K8t2Qd5sW1Z8",
  mapEmbedUrl: "https://maps.google.com/maps?q=Cafe%20Value%20654%20Spadina%20Ave%2C%20Toronto%2C%20ON%20M5S%202H7&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6631",
  longitude: "-79.4010",
  hours: ["Open 24 Hours"],
  seoTitle: "Cafe Value | Weed Dispensary in Toronto",
  metaDescription: "Cafe Value is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Spadina Ave", "The Annex", "Bloor St W"],
  introVariant: "Welcome to Cafe Value, your premier weed dispensary in Toronto situated right on 654 Spadina Ave. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near The Annex / Spadina or a weed shop near The Annex, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant The Annex / Spadina district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Metered street parking is available along Spadina Avenue",
  transitNote: "Steps from Spadina subway station and easily accessible via TTC streetcar and subway routes.",
  sectionTitle: "Serving Customers Near The Annex in Toronto"
};
